// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe8E-9ouxHuJxhUgpbhpOPMe1KlSc0bxw',
    appId: '1:92208735337:web:d104164f1576bed77c2ef8',
    messagingSenderId: '92208735337',
    projectId: 'm3cs2515c',
    authDomain: 'm3cs2515c.firebaseapp.com',
    storageBucket: 'm3cs2515c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowbFNdlcI643s8UkM_NmYAC-FSg_ng0I',
    appId: '1:92208735337:android:3af9f0b314e53a947c2ef8',
    messagingSenderId: '92208735337',
    projectId: 'm3cs2515c',
    storageBucket: 'm3cs2515c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCzl0E8h6c2w0VMvvv11dzGZOSNYtkCE',
    appId: '1:92208735337:ios:8d6b2a794bb8d2697c2ef8',
    messagingSenderId: '92208735337',
    projectId: 'm3cs2515c',
    storageBucket: 'm3cs2515c.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVCzl0E8h6c2w0VMvvv11dzGZOSNYtkCE',
    appId: '1:92208735337:ios:1a75df0b0a3409457c2ef8',
    messagingSenderId: '92208735337',
    projectId: 'm3cs2515c',
    storageBucket: 'm3cs2515c.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
